CREATE TABLE users(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(15) NOT NULL CHECK (char_length(name) >= 2),
    surname    VARCHAR(25) NOT NULL CHECK (char_length(surname) >= 2),
    birth_date DATE        NOT NULL,
    email      VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE card_info(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INT REFERENCES users (id),
    number          INT         NOT NULL UNIQUE,
    holder          VARCHAR(40) NOT NULL CHECK (char_length(holder) >= 5 AND holder = UPPER(holder)),
    expiration_date DATE        NOT NULL
);