name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
          DOCKER_HOST: tcp://localhost:2375


