name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Validate Docker
        run: |
          docker info
          docker run --rm hello-world
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
        env:
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          DOCKER_HOST: tcp://localhost:2375
          TESTCONTAINERS_RYUK_DISABLED: "true"



